routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('add-item',ItemController::class);
Route::resource('borrow-item',BorrowController::class);
Route::resource('loan',LoanDataController::class);

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/profile', 'ProfileController@index')->name('profile');
Route::put('/profile', 'ProfileController@update')->name('profile.update');


Route::get('/add-item', 'ItemController@index')->name('add-item');
Route::get('/delete-item/{id}', 'ItemController@destroy')->name('delete-item');
Route::get('/edit-item/{id}', 'ItemController@edit')->name('edit-item');
Route::get('/loan-data', 'LoanDataController@index')->name('loan-data');

Route::get('/borrow-item', 'BorrowController@index')->name('borrow-item');
Route::get('/borrow-edit/{id}', 'BorrowController@edit')->name('borrow-edit');
Route::get('/borrow-delete/{delete}', 'BorrowController@destroy')->name('borrow-delete');

Route::get('/loan-export', 'LoanDataController@export')->name('loan-export');

resources/views/about.blade.php
@extends('layouts.admin')

@section('main-content')

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">{{ __('Dashboard') }}</h1>

    @if (session('success'))
    <div class="alert alert-success border-left-success alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    @endif

    @if (session('status'))
        <div class="alert alert-success border-left-success" role="alert">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
                            <div class="row no-gutters align-items-center">
                                <div class="col-auto">
                                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm mr-2">
                                        <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Users -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">{{ __('Users') }}</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800"></div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-6 mb-4">

            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
                </div>
                <div class="card-body">
                    <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
                    <div class="progress mb-4">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </div>
            </div>

            <!-- Color System -->
            <div class="row">
                <div class="col-lg-6 mb-4">
                    <div class="card bg-primary text-white shadow">
                        <div class="card-body">
                            Primary
                            <div class="text-white-50 small">#4e73df</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-success text-white shadow">
                        <div class="card-body">
                            Success
                            <div class="text-white-50 small">#1cc88a</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-info text-white shadow">
                        <div class="card-body">
                            Info
                            <div class="text-white-50 small">#36b9cc</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-warning text-white shadow">
                        <div class="card-body">
                            Warning
                            <div class="text-white-50 small">#f6c23e</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-danger text-white shadow">
                        <div class="card-body">
                            Danger
                            <div class="text-white-50 small">#e74a3b</div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-secondary text-white shadow">
                        <div class="card-body">
                            Secondary
                            <div class="text-white-50 small">#858796</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="col-lg-6 mb-4">

            <!-- Illustrations -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{{ asset('img/svg/undraw_editable_dywm.svg') }}" alt="">
                    </div>
                    <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                    <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw →</a>
                </div>
            </div>

            <!-- Approach -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
                </div>
                <div class="card-body">
                    <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
                    <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/add-item.blade.php
@extends('layouts.admin')


{{-- modal add item --}}
<div class="modal fade" id="modalAddItem" tabindex="-1" aria-labelledby="modalAddItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalAddItem">Add New Items</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('add-item.store') }}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="item_name">Item Name</label>
                        <input type="text" id="item_name" name="item_name" value="{{ old('') }}" placeholder="Insert Item Name" class="form-control">
                        {{-- @error('nama_barang') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="specification">Specification</label>
                        <input type="text" id="specification" name="specification" value="{{ old('') }}" placeholder="Insert Specification" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="condition">Condition</label>
                        <select name="condition" id="condition" class="form-control">
                            <option selected>-- Select --</option>
                            <option value="Good">Good</option>
                            <option value="Repair">Repair</option>
                            <option value="Damaged">Damaged</option>
                            <option value="Need Repair">Need Repair</option>
                            <option value="Slightly Broken">Slightly Broken</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="location">Location</label>
                        <input type="text" id="location" name="location" value="{{ old('') }}" placeholder="Insert Location" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="item_qty">Item Qty</label>
                        <input type="number" id="item_qty" name="item_qty" value="{{ old('') }}" placeholder="Insert Item Qty" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="item_source">Item Source</label>
                        <input type="text" id="item_source" name="item_source" value="{{ old('') }}" placeholder="Insert Item Source" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{-- modal edit item --}}

<!-- Modal edit user -->
<div class="modal fade" id="modalEditItem" tabindex="-1" aria-labelledby="modalEditItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalEditItem">Edit User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="" method="post" class="formEditItem">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <div class="form-group">
                        <label for="item_name">Nama Barang</label>
                        <input type="text" id="item_name" name="item_name" placeholder="Nama Barang" class="form-control edititem_name" required>
                    </div>
                    <div class="form-group">
                        <label for="specification">Specification</label>
                        <input type="text" id="specification" name="specification" placeholder="Nama Barang" class="form-control editspecification" required>
                    </div>
                    <div class="form-group">
                        <label for="location">Location</label>
                        <input type="text" id="location" name="location" placeholder="Nama Barang" class="form-control editlocation" required>
                    </div>
                    <div class="form-group">
                        <label for="condition">Condition</label>
                        <input type="text" id="condition" name="condition" placeholder="Nama Barang" class="form-control editcondition" required>
                    </div>
                    <div class="form-group">
                        <label for="item_qty">Item Qty</label>
                        <input type="number" id="item_qty" name="item_qty" placeholder="Nama Barang" class="form-control edititem_qty" required>
                    </div>
                    <div class="form-group">
                        <label for="item_source">Item Source</label>
                        <input type="text" id="item_source" name="item_source" placeholder="Nama Barang" class="form-control edititem_source" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-user-edit"></i></i> Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section('main-content')

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col"><h4>Item List</h4></div>
            <div class="col text-right">
                <button type="button" href="#!" class="btn btn-primary" data-toggle="modal" data-target="#modalAddItem"><i class="fas fa-plus-circle"></i> Add Items</button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="example" class="table table-striped table-responsive-md" style="width:100%">
            <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>Item Name</th>
                    <th>Specification</th>
                    <th>Location</th>
                    <th>Condition</th>
                    <th>Qty</th>
                    <th>Source</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($add_item as $item)
                    <tr>
                        <td class="text-center">{{ $loop->iteration }}</td>
                        <td>{{ $item->item_name }}</td>
                        <td>{{ $item->specification }}</td>
                        <td>{{ $item->location }}</td>
                        <td>{{ $item->condition }}</td>
                        <td>{{ $item->item_qty }}</td>
                        <td>{{ $item->item_source }}</td>
                        <td class="d-flex text-center">
                            <button class="btn btn-warning mr-1" data-id="{{ $item->id }}" onclick="triggerEdit({{ $item->id }})"><i class="fas fa-user-edit mr-1"></i></a></button>
                            <a class="btn btn-danger ml-1" href="{{ url('/delete-item', $item->id) }}" role="button"><i class="fas fa-trash"></i></a>
                            {{-- <button class="btn btn-warning btn-block mr-2 align-items-center" ><i class="fas fa-user-edit mr-1"></i></a>
                            <button class="btn btn-warning btn-block mr-2 align-items-center" ><i class="fas fa-user-edit mr-1"></i></a>
                            <button class="btn btn-danger btn-block align-items-center" ><i class="fas fa-trash-alt mr-1"></i></button> --}}
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready( function () {
        $('#example').DataTable();
    } );


    function triggerEdit(id) {
        console.log("Hai")
       $.ajax({
           url: "{{ route('add-item.show','') }}/"+id,
           type: "GET",
           success: function(res){
               console.log(res)

               var elForm = document.querySelector("#modalEditItem form")
               elForm.setAttribute("action", "{{ url('add-item','') }}/"+id)
               $("#modalEditItem").modal('show');
                console.log(res.project);
               $("#modalEditItem .edititem_name").val(res.item_name);
               $("#modalEditItem .editlocation").val(res.location);
               $("#modalEditItem .editcondition").val(res.condition);
               $("#modalEditItem .edititem_qty").val(res.item_qty);
               $("#modalEditItem .editspecification").val(res.specification);
               $("#modalEditItem .edititem_source").val(res.item_source);
           },
           error: function(err){
                console.log(err)
           }
       })
    }

    $(document).ready(function() {
        console.log('tes')
        $('#triggerEdit').click(function(e) {
            console.log('s');
            let id = $(this).attr('data-id');
            console.log('a');
            console.log("{{ route('add-item.show','') }}/" + id)
            $.get({
                url: "{{ route('add-item.show','') }}/" + id,
                data: {
                    '_token': $('meta[name=csrf-token]').attr('content'),
                },
                success: function(res) {
                    console.log('sukses nih');
                    console.log(res);

                    $(".edititem_name").val(res.item_name);
                    $(".editspecification").val(res.specification);
                    $(".editlocation").val(res.location);
                    $(".editcondition").val(res.condition);
                    $(".edititem_qty").val(res.item_qty);
                    $(".edititem_source").val(res.item_source);
                },
                error: function(err) {
                    console.log('gagal');
                    console.log(err)
                }
            })
        });
    });

</script>
@endsection

resources/views/add.blade.php
@extends('layouts.admin')

@section('main-content')

<div class="card">
    <div class="card-header ">
        <p>Tabel User</p>
        <a class="btn btn-warning float-right" href="#" role="button">Add User</a>
    </div>
    <div class="card-body">
        <table id="example" class="table table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Office</th>
                    <th>Age</th>
                    <th>Start date</th>
                    <th>Salary</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Tiger Nixon</td>
                    <td>System Architect</td>
                    <td>Edinburgh</td>
                    <td>61</td>
                    <td>2011/04/25</td>
                    <td>$320,800</td>
                </tr>
                <tr>
                    <td>Jenette Caldwell</td>
                    <td>Development Lead</td>
                    <td>New York</td>
                    <td>30</td>
                    <td>2011/09/03</td>
                    <td>$345,000</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready( function () {
        $('#example').DataTable();
    } );
</script>
@endsection

resources/views/borrow-item.blade.php
@extends('layouts.admin')

<div class="modal fade" id="modalAddItem" tabindex="-1" aria-labelledby="modalAddItem" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalAddItem">Borrow Items</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('borrow-item.store') }}" method="post">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="borrower">Insert Borrower Name</label>
                        <input type="text" id="borrower" name="borrower" value="{{ Auth::user()->name }}" value="{{ old('') }}" placeholder="Insert Insert Borrower Name" class="form-control" readonly>
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="user_id">Insert Borrower Name</label>
                        <input type="text" id="user_id" name="user_id" value="{{ Auth::user()->id }}" value="{{ old('') }}" placeholder="Insert Insert Borrower Name" class="form-control" readonly>
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="">Borrow Date</label>
                        <input type="date" class="form-control" name="borrow_date" id="borrow_date" value="{{ old('') }}" placeholder="Insert Borrow Date">
                    </div>
                    <div class="form-group">
                        <label for="">Items</label>
                        <select name="item_name" id="item_name" value="{{ old('') }}" class="form-control editItem">
                            <option selected>-- Select --</option>
                            @foreach($get_item as $item)
                            <option value="{{ $item->item_name }}">{{ $item->item_name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group" type="hidden">
                        <label for="">Items</label>
                        <select name="item_id" id="item_id" value="{{ old('') }}" class="form-control editItem">
                            <option selected>-- Select --</option>
                            @foreach($get_item as $item)
                            <option value="{{ $item->id }}">{{ $item->id }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="">Condition</label>
                        <select name="condition" id="condition" value="{{ old('') }}" class="form-control editCondition">
                            <option selected>-- Select --</option>
                            @foreach($get_item as $item)
                            <option value="{{ $item->condition }}">{{ $item->condition }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="item_qty">Item Qty</label>
                        <input type="number" id="item_qty" name="item_qty" value="" value="{{ old('') }}" placeholder="Insert Item Qty" class="form-control">
                        {{-- @error('harga') <code>{{ $message }}</code> @enderror --}}
                    </div>
                    <div class="form-group">
                        <label for="">Return Date</label>
                        <input type="date" class="form-control" name="return_date" id="return_date" value="{{ old('') }}" placeholder="Insert Return Date">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fas fa-times-circle"></i> Close</button>
                    <button type="submit" class="btn btn-primary"><i class="fas fa-plus-circle"></i> Add</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section('main-content')

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col"><h4>Item List</h4></div>
            <div class="col text-right">
                <button type="button" href="#!" class="btn btn-primary" data-toggle="modal" data-target="#modalAddItem"><i class="fas fa-plus-circle"></i> Borrow Items</button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="example" class="table table-striped" style="width:100%">
            <thead>
                <tr class="text-center">
                    <th>#</th>
                    <th>Borrower</th>
                    <th>Borrow Date</th>
                    <th>Item Name</th>
                    <th>Qty</th>
                    <th>Condition</th>
                    <th>Return Date</th>
                    <th>Action</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($view_borrow as $item)
                <tr class="text-center">
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $item->borrower }}</td>
                        <td>{{ date('d-m-Y', strtotime($item->borrow_date)); }}</td>
                        <td>{{ $item->item_borrowed }}</td>
                        <td>{{ $item->item_qty }}</td>
                        <td>{{ $item->condition }}</td>
                        <td>{{ date('d-m-Y', strtotime($item->return_date)); }}</td>
                        <td class="text-center">
                            <a class="btn btn-danger ml-1" href="{{ url('/borrow-delete', $item->id) }}" role="button"><i class="fas fa-trash"></i></a>
                            {{-- <button class="btn btn-warning btn-block mr-2 align-items-center" ><i class="fas fa-user-edit mr-1"></i></a>
                            <button class="btn btn-warning btn-block mr-2 align-items-center" ><i class="fas fa-user-edit mr-1"></i></a>
                            <button class="btn btn-danger btn-block align-items-center" ><i class="fas fa-trash-alt mr-1"></i></button> --}}
                        </td>
                        <td></td>
                    </tr>
                    @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(document).ready( function () {
        $('#example').DataTable();
    } );
</script>
@endsection